import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/modules/header/Header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" dir="rtl">
            <body className="font-iransans-regular">
                <Header />
                {children}
            </body>
        </html>
    );
}
